Initial reorganization
sidratresearch/qp pull request #1
Opened 2024-12-18 17:53 UTC by jscora

This has created some more subfolders to further modularize the code. In utils, test_data should be moved to tests in future iterations as the create_test_data functions within parameterizations are also moved to test files. factory.py needs to undergo some changes, and when it does it should be renamed appropriately. Also, pdf_gen was renamed base_parameterization and now lives in the parameterizations folder

2025-01-06 16:59 UTC, mubdi requested changes
A few files that look like they're not supposed to be in the repo

2025-01-06 16:59 UTC, mubdi commented on test_dict.hdf5
Don't think this is supposed to be here?

2025-01-06 16:59 UTC, mubdi commented on test_normancil.pq
Don't think this is supposed to be here?

2025-01-07 15:19 UTC, jscora commented on test_dict.hdf5
This was a file generated by testing, so I've deleted it

2025-01-07 15:19 UTC, jscora commented on test_normancil.pq
This was a file generated by testing, so I've deleted it

2025-01-07 20:21 UTC, mubdi approved these changes
LGTM!

2025-01-07 20:21 UTC, merged